name: Generate Snake Animation

on:
  schedule:
    # 每天的 UTC 时间 12 点自动运行
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout
        uses: actions/checkout@v2

      # 使用 Platane 的 snk Action 生成蛇形动画
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: "Mikalasa"  # 替换为你的 GitHub 用户名
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 确保生成的文件存在
      - name: Check output
        run: |
          ls dist
          test -f dist/github-contribution-grid-snake.svg
          test -f dist/github-contribution-grid-snake-dark.svg

      # 发布到 output 分支
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
